/** Países o regiones de referencia (español) por desfase UTC en minutos. */
export const OFFSET_REFERENCES_ES: Record<number, string> = {
  [-660]: "Samoa americana, Niue",
  [-600]: "Hawái, Tahití",
  [-570]: "Polinesia francesa (Marquesas)",
  [-540]: "Estados Unidos (Aleutianas)",
  [-480]: "Alaska",
  [-420]: "México (Pacífico), Arizona",
  [-360]: "México, Estados Unidos (centro)",
  [-300]: "Colombia, Perú, Ecuador",
  [-240]: "Venezuela, Bolivia, Paraguay",
  [-180]: "Argentina, Brasil, Uruguay",
  [-150]: "Canadá (Terranova)",
  [-120]: "Groenlandia, Fernando de Noronha",
  [-60]: "Azores, Cabo Verde",
  0: "Reino Unido, Portugal, Marruecos",
  60: "España, Francia, Alemania",
  120: "Grecia, Sudáfrica, Finlandia",
  180: "Turquía, Arabia Saudí, Kenia",
  210: "Irán",
  240: "Emiratos Árabes, Azerbaiyán",
  270: "Afganistán",
  300: "Pakistán, Kazajistán, Uzbekistán",
  330: "India, Sri Lanka",
  345: "Nepal",
  360: "Bangladesh, Kirguistán",
  390: "Myanmar, Islas Cocos",
  420: "Tailandia, Vietnam, Indonesia (oeste)",
  480: "China, Singapur, Filipinas",
  525: "Australia (Eucla)",
  540: "Japón, Corea del Sur",
  570: "Australia (centro)",
  600: "Australia (este), Papúa Nueva Guinea",
  630: "Australia (Lord Howe)",
  660: "Rusia (Magadán), Nueva Caledonia",
  720: "Fiyi, Rusia (Kamchatka), Nueva Zelanda",
  765: "Nueva Zelanda (Chatham)",
  780: "Samoa, Tonga",
  840: "Kiribati (Línea)",
};

/** Zona IANA de referencia por desfase (sin horario de verano cuando es posible). */
export const CANONICAL_ZONE_BY_OFFSET: Record<number, string> = {
  [-660]: "Pacific/Pago_Pago",
  [-600]: "Pacific/Honolulu",
  [-570]: "Pacific/Marquesas",
  [-540]: "America/Adak",
  [-480]: "America/Anchorage",
  [-420]: "America/Phoenix",
  [-360]: "America/Mexico_City",
  [-300]: "America/Bogota",
  [-240]: "America/Caracas",
  [-180]: "America/Argentina/Buenos_Aires",
  [-150]: "America/St_Johns",
  [-120]: "America/Noronha",
  [-60]: "Atlantic/Cape_Verde",
  0: "UTC",
  60: "Europe/Madrid",
  120: "Europe/Athens",
  180: "Europe/Istanbul",
  210: "Asia/Tehran",
  240: "Asia/Dubai",
  270: "Asia/Kabul",
  300: "Asia/Karachi",
  330: "Asia/Kolkata",
  345: "Asia/Katmandu",
  360: "Asia/Dhaka",
  390: "Asia/Rangoon",
  420: "Asia/Bangkok",
  480: "Asia/Shanghai",
  525: "Australia/Eucla",
  540: "Asia/Tokyo",
  570: "Australia/Adelaide",
  600: "Australia/Sydney",
  630: "Australia/Lord_Howe",
  660: "Asia/Magadan",
  720: "Pacific/Fiji",
  765: "Pacific/Chatham",
  780: "Pacific/Tongatapu",
  840: "Pacific/Kiritimati",
};
